### PR TITLE
Improving documentation

### PR DESCRIPTION
**Pull request by Ishika11**
Hi, this is Ishika, I have created created a new PR in the markdown branch. There are some spelling error corrections, grammar changes and reconstruction

### CODE REVIEW

**Comment by danielabutano** [comment]
Thanks @Ishika11.
As I said @SanniM3 has already migrated all the documentation (into markdown files) on the new markdow branch. 
This PR involves .rst files which do not exist anymore, because migrated to .md.
We have 2 options.
I can ask @SanniM3 to apply manually your changes (but it's a shame that you will not appear as contriubutor), or you can make a new PR wich involves .md files.
Sorry to waste your time, but as I said we are in the middle of the migration process.

**Comment by Ishika11** [comment]
Oh, I’m sorry for the redundant mistake, I’ll do the changes on the
markdown files :) thanks a lot for your patience

**Comment by danielabutano** [comment]
Thank you @Ishika11

**Comment by Ishika11** [comment]
Sure :)

**Comment by danielabutano** [comment]
@Ishika11 I have merged the PR  but @SanniM3 will work  in a new branch to adapt the structure of the directory  to Docusaurus. So better to wait. Thanks!

**Pull request closed without merging**
