### PR TITLE
Update old links

### PR DESCRIPTION
**Pull request by Persdre**

### CODE REVIEW

**Comment by sergiocontrino** [comment]
great! thanks @Persdre . could you please check my suggestions in previous comments and in case update your links? thanks!

**Comment by Persdre** [comment]
> great! thanks @Persdre . could you please check my suggestions in previous comments and in case update your links? thanks!

already updated them! thanks😊

**Comment by sergiocontrino** [comment]
i think that the compare_templates one is still incorrect :)

**Comment by Persdre** [comment]
> i think that the compare_templates one is still incorrect :)

oops, sorry for not noticing the first half of the link🤣

**Pull request merged**
