### PR TITLE
No longer are dollar signs and file paths before the dollar sign copi…

### PR DESCRIPTION
**Pull request by Igoranze**
Pull request on behalve of: https://github.com/intermine/im-docs/issues/36

Added a new enhanced JS file that processes the "to copy" data before adding to the clipboard.
This replaces the original "to copy" data from Sphinx. While it works the same, this new enhanced copy data file removes all $ and file paths before the $.

Tested with all "to copy" values on the "get-started/tutorial/index.html" page.

### CODE REVIEW

**Comment by yochannah** [comment]
@Igoranze quick question - when I run this locally it still seems to use the old copy-button script (I can see it loading, and not your new one, in my browser network panel). It's also the same in the readthedocs preview: https://external-builds.readthedocs.io/html/intermine/38/get-started/tutorial/index.html any thoughts?

**Comment by Igoranze** [comment]
@yochannah I'm sorry, I don't have time untill monday to look at this problem.

**Comment by yochannah** [comment]
that's fine! :)

**Comment by Igoranze** [comment]
> @Igoranze quick question - when I run this locally it still seems to use the old copy-button script (I can see it loading, and not your new one, in my browser network panel). It's also the same in the readthedocs preview: https://external-builds.readthedocs.io/html/intermine/38/get-started/tutorial/index.html any thoughts?

Hi @yochannah 
When I open this link, I can't seem to find my javascript file EnhancedCopyButton.js in the loaded resources, are you sure that this build contains my changes?

**Comment by yochannah** [comment]
@Igoranze - it seems to be the same if I pull your changes and build the docs locally

**Comment by Igoranze** [comment]
@yochannah How right you are,
I tried it localy today and also the same thing. I messed up somewhere. Will get back @ u soon :)
tbc

**Comment by fequerver** [comment]
Maybe the js is cached? Try to erase the browser cache and try again.

**Comment by Igoranze** [comment]
Hi, So sorry, it's been a while. But I finally had time again (in between work and kids). I upgraded the Sphinx library to 1.8.5 with pip `pip install --upgrade sphinx` and did a `pip freeze > requirements.txt` to import all changes into the requirements.txt file. Since 1.8.5 also has some libraries that are needed, these are also imported into the requirements.txt. 

But since Python2.7 is EndOfLife since 01-01-2020 we should consider upgrading everything to Python3.7 and up? But that would be a new ticket/issue imo.

**Comment by uosl** [comment]
Hello @Igoranze 

Thank you for your contribution. We will test and review it soon.

Regarding upgrading to Python 3.7, we plan to migrate the documentation to Markdown and a JS static doc site generator, (to make it consistent with our other docs) once we have the resources.

**Review by uosl — APPROVED** [review]
Well documented and works great :100: 
Thanks for the help!

**Pull request merged**
